### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by momon** [Jako/ResSaveSort#12]
I'm not entirely sure if I am using this for the right reasons but when I found it I was expecting to be able to sort a specific container child resources by an arbitrary field and in a specific order.  In my case, I tried to setup a config for my Blog entries container (ID 55) by publishedon in desc order.

I was expecting on refresh to have a list of entries ordered from more recent to older in that particular folder but that's not the case.  The list remains ordered by menuindex instead.  So I am a bit unsure if perhaps I missunderstood the purpose of the plugin, or I may not be using it correctly or perhaps it is just broken.

**Comment by momon** [comment]
Well, that's a bit embarrassing, right after posting this I went back to the website and continued doing other work and suddenly I realized the tree ordered as expected? it is very odd because I had repeatedly refreshed that tree over and over before and even the entire window itself and it was not updating.  After a few minutes it appears to update on its own? seems to be working now but that's very odd.

**Comment by Jako** [comment]
The plugin that sorts the resources does not refresh the tree. Maybe that's the issue.

It would be some work to refresh the tree after saving a resource and even more work to refresh the children of the parent of the current resource. This has to be done using Javascript. For this reason, I have decided not to implement this.
